---
cacerts2_ca_server: "{{ groups['cacerts_server'][0] }}"
cacerts2_ca_dir: /vagrant/.ca
cacerts2_ca_domain:
  common_name: c2d
  cipher: auto
  passphrase: supersecure # vault
  create: ['key','csr', 'crt', 'p12', 'pem']

common_cacerts_enable: yes
cacerts_os_ca_pem_urls:
  - "file:////vagrant/.ca/c2d/c2d.crt"
