---
ansible_python_interpreter: /usr/bin/python3
alias_prefix: c2d

c2_common_packages_extra_default:
  Ubuntu 18:
    - nano
    - wget
    - tree
    - unzip
    - zip
    - mariadb-client-core-10.1
    - jq
    - build-essential
    - python3-dev
    - python3-wheel
    - libsasl2-dev
    - libldap2-dev
    - libssl-dev
    - git
  RedHat 7:
    - nfs-utils
    - nano
    - tree
    - python-devel
    - openldap-devel
    - unzip

common_packages_extra: "{{ c2_common_packages_extra_default|combine(c2_common_packages_extra_node|default({})) }}"

bootstrap_packages_extra:
  - python3-pip

common_pip_install_upgrade: pip3 install --upgrade pip

#common_etc_environment: >
#  PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin

nfs_server: nfs
nfs_mounts: []
#  - { path: /backup, src: '{{ nfs_server }}:/nfs/backup', opts: rw, fstype: nfs, state: mounted }

common_ansible_user_create: true

sudo_enabled: yes
sudo_users: [ansible, vagrant]
sudo_passwordless: [admin, sudo, ansible]
common_manage_sudoers: true

# common_ansible_authorized_keys: https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub
common_ansible_user_password: whuq0hKZYtmE2

# common_terminal_prompt: '\e[01;31m[\u@{{ inventory_hostname }} \h \w]\\$\e[m '

backup_cron_jobs: false

firewalld_disable: true

# lvm_vg_devices: ['/dev/sdb'] # ,'/dev/sdc'

common_manage_hosts: yes
# common_secrets_dir: "{{ inventory_dir }}/secret_vars" # TODO

java_version: openjdk-11-jdk
java_versions:
    openjdk-11-jdk:
      folder: java-11-openjdk-amd64 # in /usr/lib/jvm
      package: yes
      bundles:
        - alias: c2d-ca
          url: file:///vagrant/.ca/c2d/c2d.crt
