---
hosts_domain: seetoo.tech
hosts_domain_segment:
  apps: apps.dev
  mw: mw.dev

hosts_default_ipv4_hosts:
  address: "{{ ansible_eth1.ipv4.address }}"
  hostnames:
    - "{{ inventory_hostname_short }}"

hosts_additional_hosts:
  - address: "{{ hostvars[groups['microk8s'][0]].ansible_host }}"
    hostnames:
         - "{{ groups['microk8s'][0] }}.{{ hosts_domain_segment['mw'] }}.{{ hosts_domain }}"
  - address: "{{ hostvars[groups['database'][0]].ansible_host }}"
    hostnames:
      - "{{ c2_keycloak_database_host }}"
  - address: "{{ hostvars[groups['keycloak'][0]].ansible_host }}"
    hostnames:
      - "{{ groups['keycloak'][0] }}.{{ hosts_domain_segment['apps'] }}.{{ hosts_domain }}"
  - address: "{{ hostvars[groups['reverse_proxy'][0]].ansible_host }}"
    hostnames:
      - "{{ groups['reverse_proxy'][0] }}.{{ hosts_domain_segment['mw'] }}.{{ hosts_domain }}"
      - "{{ hosts_domain }}"
      - "www.{{ hosts_domain }}"
      - "keycloak.{{ hosts_domain }}"
